'use client';

import { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys will be defined here for now, but we'll move them to separate files
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.explore': 'Explore',
    'nav.trending': 'Trending',
    'nav.spin': 'Spin Wheel',
    'nav.create': 'Create',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.login': 'Login',
    'nav.signup': 'Sign up',
    'nav.createPoll': 'Create Poll',
    'nav.getStarted': 'Get Started',
    'nav.logout': 'Log Out',
    'nav.backToFeed': 'Back to Feed',
    
    // Home page
    'home.hero.title': 'What does',
    'home.hero.titleHighlight': 'everyone',
    'home.hero.titleEnd': 'think?',
    'home.hero.subtitle': 'Vote on anything. Share it instantly. See results in real time.',
    'home.createPoll': 'Create a poll →',
    'home.browsePolls': 'Browse polls',
    'home.liveNow': 'Live now',
    'home.noActivePolls': 'No active polls at the moment.',
    'home.searchPlaceholder': 'Search polls...',
    'home.trending': 'Trending',
    'home.recent': 'Recent',
    'home.expiringSoon': 'Expiring Soon',
    'home.searchResults': 'Search Results',
    'home.whatsHappening': 'What\'s happening',
    'home.loading': 'Loading...',
    'home.failedToLoad': 'Failed to load polls',
    'home.tryAgain': 'Try Again',
    'home.refreshPage': 'Refresh Page',
    
    // Footer
    'footer.createdBy': 'Created by',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.failed': 'Failed',
    'common.tryAgain': 'Try Again',
    'common.refresh': 'Refresh',
    'common.searching': 'Searching...',
    'common.unexpectedError': 'We encountered an unexpected error. Please try refreshing the page.',
    'common.contactSupport': 'If you believe this is an error, please contact our support team.',
    'common.pollNotFound': 'Poll not found',
    'common.pollNotFoundDesc': 'Poll not found. It may have been deleted or never existed.',
    'common.loadingImages': 'Loading images...',
    
    // Theme/Language
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'lang.en': 'English',
    'lang.es': 'Español',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.profileDesc': 'Manage your profile information',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Control your notification preferences',
    'settings.privacy': 'Privacy',
    'settings.privacyDesc': 'Manage your privacy settings',
    'settings.appearance': 'Appearance',
    'settings.appearanceDesc': 'Customize the app appearance',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose your preferred language',
    'settings.logout': 'Log Out',
    'settings.displayName': 'Display Name',
    'settings.displayNamePlaceholder': 'Enter your display name',
    'settings.bio': 'Bio',
    'settings.bioPlaceholder': 'Tell us about yourself',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive notifications via email',
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotificationsDesc': 'Receive push notifications on your device',
    'settings.pollReminders': 'Poll Reminders',
    'settings.pollRemindersDesc': 'Get reminded about polls you participated in',
    'settings.privateProfile': 'Private Profile',
    'settings.privateProfileDesc': 'Only followers can see your activity',
    'settings.showActivity': 'Show Activity Status',
    'settings.showActivityDesc': 'Let others see when you\'re active',
    'settings.theme': 'Theme',
    'settings.displayLanguage': 'Display Language',
    'settings.saveChanges': 'Save Changes',
    
    // Spin Wheel
    'spin.title': 'Spin the',
    'spin.titleHighlight': 'Wheel',
    'spin.subtitle': 'Can\'t decide? Let fate choose! Add your options and give the wheel a spin.',
    'spin.spin': 'SPIN',
    'spin.spinning': '...',
    'spin.currentOptions': 'Current Options',
    'spin.quickTemplates': 'Quick Templates',
    'spin.optionPlaceholder': 'Option',
    'spin.addOption': 'Add',
    'spin.add': 'Add',
    'spin.addToWheel': 'Add to Wheel',
    'spin.yesOrNo': 'Yes or No',
    'spin.foodChoice': 'Food Choice',
    'spin.activities': 'Activities',
    'spin.numbers': 'Numbers 1-6',
    'spin.theWheelHasSpoken': 'The wheel has spoken!',
    'spin.spinAgain': 'Spin Again',
    'spin.enterAtLeastTwoOptions': 'Enter at least 2 options to start spinning!',
    'spin.minimumTwoOptions': 'Minimum 2 options required',
    'spin.maximumTwelveOptions': 'Maximum 12 options allowed',
    'spin.pleaseEnterAnOption': 'Please enter an option',
    'spin.optionTextCannotBeEmpty': 'Option text cannot be empty',
    'spin.addAtLeastTwoOptionsToSpin': 'Add at least 2 options to spin',
    'spin.optionsCount': 'options (minimum 2 required to spin)',
    'spin.enterAnOption': 'Enter an option...',
    'spin.addOptionAfterThis': 'Add option after this',
    'spin.removeOption': 'Remove option',
    'spin.configureOptions': 'Configure Options',
    'spin.spinWheel': 'Spin Wheel',
    'spin.continueToWheel': 'Continue to Wheel',
    'spin.editOptions': 'Edit Options',

    // Polls & Rankings
    'poll.yourRankingSubmitted': 'Your ranking has been submitted and cannot be changed',
    'poll.pollsInvitedTo': 'Polls I\'m invited to',
    'poll.myPrivatePolls': 'My Private Polls',
    'poll.myPublicPolls': 'My Public Polls',
    'poll.onlyLinkAccess': 'Only people with this link can see this poll',
    'poll.copyInviteLink': 'Copy invite link',
    'poll.acceptInvite': 'Accept invite & view poll',
    'poll.invalidInvite': 'Invalid or expired invite link',
    'poll.noAccess': 'You don\'t have access to this poll',
    'poll.noRankings': 'No rankings submitted yet',
    'poll.submitRanking': 'Submit Ranking',
    'poll.rankPoll': 'Rank Poll',
    'poll.votePoll': 'Vote Poll',
    'poll.private': 'Private',
    'poll.public': 'Public',
    'poll.emojiOptional': 'Emoji (optional)',
    'poll.share': 'Share',
    'poll.copied': '✓ Copied!',
    'poll.delete': 'Delete',
    'poll.deleteConfirm': 'Are you sure you want to delete this poll? This cannot be undone.',
    'poll.cancel': 'Cancel',
    'poll.viewPoll': 'View poll',
    'poll.noVotesYet': 'No votes yet. Be the first!',
    'poll.active': 'Active',
    'poll.ended': 'Ended',
    'poll.myPolls': 'My Polls',
    'poll.deletePoll': 'Delete poll',
    'poll.voteOnPoll': 'Vote on poll',
    'poll.results': 'Results',
    'poll.dangerZone': 'Danger zone',
    
    // Create Poll Form
    'create.titleRequired': 'Ranking title is required',
    'create.pollTitleRequired': 'Poll title is required',
    'create.titleMinLength': 'Title must be at least 3 characters long',
    'create.titleMaxLength': 'Title must be less than 100 characters',
    'create.minOptions': 'At least 2 options are required',
    'create.maxOptions': 'Maximum 10 options allowed',
    'create.duplicateOptions': 'Duplicate options are not allowed',
    'create.minParticipants': 'Private polls require at least one participant',
    'create.failed': 'Failed to create poll. Please try again.',
    'create.failedRanking': 'Failed to create ranking. Please try again.',
    'create.creating': 'Creating...',
    'create.optionRequired': 'Option is required',
    'create.optionMinLength': 'Option must be at least 1 character long',
    'create.newVote': 'Create a New Vote',
    'create.newRanking': 'Create a New Ranking',
    'create.newPoll': 'Create a New Poll',
    'create.description': 'Share your thoughts and gather opinions from your community',
    'create.back': 'Back',
    
    // My Polls
    'myPolls.createdBy': 'Created by',
    'myPolls.noPolls': 'You haven\'t created any polls yet',
    'myPolls.startCreating': 'Start by creating your first poll!',
    'myPolls.createFirst': 'Create Your First Poll',

    // Navbar specific
    'nav.hello': 'Hello',
    'nav.changeName': 'Change name',
    'nav.createVote': 'Create Vote',
    'nav.createRanking': 'Create Ranking',
    'nav.createRating': 'Create Rating',
    'nav.spinWheel': 'Spin Wheel',
    'nav.createVersus': 'Create Versus',
    'nav.votes': 'Votes',
    'nav.ranking': 'Ranking',
    'nav.ratings': 'Ratings',
    'nav.versus': 'Versus',
    'nav.vote': 'Vote',
    'nav.changeYourName': 'Change your name',
    'nav.yourNewName': 'Your new name...',
    'nav.save': 'Save',
    'nav.yourName': 'Your name',
    'nav.placeholder': 'Enter your name',

    // Home page specific
    'home.subtitle': 'Create polls, rankings, ratings and spin wheels — share them with anyone.',
    'home.recentActivity': 'Recent activity',
    'home.noActivityYet': 'No activity yet — be the first to create something!',
    'home.votesDesc': 'Ask a question, let people choose an answer',
    'home.rankingDesc': 'Let people rank options by preference',
    'home.ratingsDesc': 'Rate and compare items with stars',
    'home.spinDesc': 'Spin to decide randomly',
    'home.rankingBadge': 'Ranking',
    'home.voteBadge': 'Vote',

    // PollCard specific
    'poll.closingIn': 'Closing in',
    'poll.votes': 'votes',

    // Versus specific
    'versus.tournamentCreated': 'Tournament created',
    'versus.completePreviousRound': 'Complete the previous round first',
    'versus.completeAllDuels': 'Complete all duels before submitting',
    'versus.shareResult': 'Share Result',
    'versus.generating': 'Generating...',
    'versus.copied': 'Copied!',
    'versus.downloaded': 'Downloaded!',
    'versus.error': 'Error',
    'versus.expired': 'Expired',
    'versus.completed': 'Completed',
    'versus.loadingTournament': 'Loading tournament...',
    'versus.by': 'by',
    'versus.options': 'options',
    'versus.share': 'Share',
    'versus.comp': 'Share',
    'versus.submitBracket': 'Submit Bracket',
    'versus.submit': 'Submit',
    'versus.result': 'Result',
    'versus.bracketOf': 'Bracket of',
    'versus.anonymous': 'Anonymous',
    'versus.days': 'd',
    'versus.hours': 'h',
    'versus.minutes': 'm',
    'versus.seconds': 's',

    // Explore page
    'explore.title': 'Explore Polls',
    'explore.subtitle': 'Discover and participate in polls from the community',
    'explore.searchPlaceholder': 'Search polls by title or options...',
    'explore.sortBy': 'Sort by:',
    'explore.mostRecent': 'Most Recent',
    'explore.newlyCreated': 'Newly created polls',
    'explore.mostPopular': 'Most Popular',
    'explore.highestVoteCount': 'Highest vote count',
    'explore.trending': 'Trending',
    'explore.popularRecent': 'Popular recent polls',
    'explore.endingSoon': 'Ending Soon',
    'explore.pollsClosingSoon': 'Polls closing soon',
    'explore.found': 'Found',
    'explore.pollsMatching': 'polls matching',
    'explore.showing': 'Showing',
    'explore.polls': 'polls',
    'explore.noPollsFound': 'No polls found',
    'explore.noPollsAvailable': 'No polls available',
    'explore.tryAdjusting': 'Try adjusting your search terms or browse all polls',
    'explore.beFirst': 'Be the first to create a poll and get started!',
    'explore.clearSearch': 'Clear Search',
    'explore.createPoll': 'Create a Poll',

    // My Polls page
    'myPolls.noPublicPolls': 'No public polls yet',
    'myPolls.createFirstPublic': 'Create your first public poll to share with everyone!',
    'myPolls.createPoll': 'Create Poll',
    'myPolls.noPrivatePolls': 'No private polls yet',
    'myPolls.createPrivateDesc': 'Create a private poll to share only with specific participants.',
    'myPolls.createPrivatePoll': 'Create Private Poll',
    'myPolls.invitedTo': 'Polls I\'m Invited To',
    'myPolls.noPendingInvites': 'No pending invites',
    'myPolls.invitesDesc': 'When someone invites you to a private poll, it will appear here.',

    // EmptyPollsState
    'empty.createFirstPoll': 'Create Your First Poll!',
    'empty.description': 'Share your opinion and discover what your community thinks. It\'s easy, fast, and fun.',
    'empty.createPollNow': 'Create Poll Now',
    'empty.tryWheel': 'Try the Wheel',
    'empty.easyVoting': 'Easy Voting',
    'empty.easyVotingDesc': 'Create polls in seconds with multiple options',
    'empty.decisionWheel': 'Decision Wheel',
    'empty.decisionWheelDesc': 'Let fate decide for you',
    'empty.trending': 'Trending',
    'empty.trendingDesc': 'Discover the most popular polls',
    'empty.bestDecisions': 'The best decisions are made together',

    // Votes page
    'votes.title': 'Votes',
    'votes.subtitle': 'Vote on your favorite options',
    'votes.createVote': 'Create Vote',
    'votes.recent': 'Recent',
    'votes.loadingVotes': 'Loading votes...',
    'votes.noVotesYet': 'No votes yet',
    'votes.beFirst': 'Be the first to create a vote!',

    // Create Poll Form
    'form.pollBasics': 'Poll Basics',
    'form.pollType': 'Poll Type',
    'form.votePoll': 'Vote Poll',
    'form.votePollDesc': 'Each person picks one option',
    'form.rankPoll': 'Rank Poll',
    'form.rankPollDesc': 'Order all options by preference',
    'form.pollTitle': 'Poll Title',
    'form.whatsPollAbout': 'What\'s your poll about?',
    'form.whatsRankingAbout': 'What\'s your ranking about?',
    'form.searchStockImages': '📷 Search Stock Images',
    'form.removeTitleImage': 'Remove title image',
    'form.titleImagePreview': 'Title image preview',
    'form.characters': 'characters',
    'form.description': 'Description (Optional)',
    'form.addDetailsPoll': 'Add more details about your poll...',
    'form.addDetailsRanking': 'Add more details about your ranking...',
    'form.expiration': 'Expiration',
    'form.willClose': 'Poll will automatically close after the selected duration',
    'form.pollOptions': 'Poll Options',
    'form.addOptionsRank': 'Add at least 2 options to rank. You can include text, emoji, or upload an image for each option.',
    'form.addOptions': 'Add at least 2 options. You can include text, emoji, or upload an image for each option.',
    'form.option': 'Option',
    'form.stockImages': '📷 Stock Images',
    'form.optionPreview': 'Option preview',
    'form.removeImage': 'Remove image',
    'form.youNeedAtLeast': 'You need at least 2 options',
    'form.removeOption': 'Remove option',
    'form.addOption': '+ Add Option',
    'form.visibilityPrivacy': 'Visibility & Privacy',
    'form.public': 'Public - Anyone with the link can view and vote',
    'form.publicRank': 'Public - Anyone with the link can view and rank',
    'form.private': 'Private - Only invited participants can view and vote',
    'form.privateRank': 'Private - Only invited participants can view and rank',
    'form.privateLock': '🔒 Only people you share the invite link with can see this poll',
    'form.privateLockRank': '🔒 Only people you share the invite link with can see this ranking',
    'form.privateWarning': '⚠️ Private polls require at least one participant',
    'form.privateWarningRank': '⚠️ Private rankings require at least one participant',
    'form.anonymousVoting': 'Anonymous voting (participants\' votes are hidden)',
    'form.inviteParticipants': 'Invite Participants',
    'form.enterEmail': 'Enter email or username',
    'form.invitedParticipants': 'Invited Participants:',
    'form.removeParticipant': 'Remove participant',
    'form.duration.15min': '15 minutes',
    'form.duration.30min': '30 minutes',
    'form.duration.1h': '1 hour',
    'form.duration.3h': '3 hours',
    'form.duration.6h': '6 hours',
    'form.duration.12h': '12 hours',
    'form.duration.24h': '24 hours',
    'form.duration.48h': '48 hours',
    'form.duration.7d': '7 days',
    'form.onlyJpgPng': 'Only JPG and PNG images are allowed',
    'form.imageSize': 'Image size must be less than 5MB',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.explore': 'Explorar',
    'nav.trending': 'Tendencias',
    'nav.spin': 'Girar Ruleta',
    'nav.create': 'Crear',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'nav.login': 'Iniciar Sesión',
    'nav.signup': 'Registrarse',
    'nav.createPoll': 'Crear Encuesta',
    'nav.getStarted': 'Comenzar',
    'nav.logout': 'Cerrar Sesión',
    'nav.backToFeed': 'Volver al Feed',
    
    // Home page
    'home.hero.title': '¿Qué opinas',
    'home.hero.titleHighlight': 'tú',
    'home.hero.titleEnd': '?',
    'home.hero.subtitle': 'Vota sobre cualquier cosa. Comparte instantáneamente. Ve los resultados en tiempo real.',
    'home.createPoll': 'Crear encuesta →',
    'home.browsePolls': 'Explorar encuestas',
    'home.liveNow': 'En vivo',
    'home.noActivePolls': 'No hay encuestas activas en este momento.',
    'home.searchPlaceholder': 'Buscar encuestas...',
    'home.trending': 'Tendencias',
    'home.recent': 'Recientes',
    'home.expiringSoon': 'Terminan Pronto',
    'home.searchResults': 'Resultados de Búsqueda',
    'home.whatsHappening': 'Qué está pasando',
    'home.loading': 'Cargando...',
    'home.failedToLoad': 'Error al cargar encuestas',
    'home.tryAgain': 'Intentar de Nuevo',
    'home.refreshPage': 'Actualizar Página',
    
    // Footer
    'footer.createdBy': 'Creado por',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.failed': 'Falló',
    'common.tryAgain': 'Intentar de Nuevo',
    'common.refresh': 'Actualizar',
    'common.searching': 'Buscando...',
    'common.unexpectedError': 'Encontramos un error inesperado. Por favor intenta actualizar la página.',
    'common.contactSupport': 'Si crees que esto es un error, por favor contacta a nuestro equipo de soporte.',
    'common.pollNotFound': 'Encuesta no encontrada',
    'common.pollNotFoundDesc': 'Encuesta no encontrada. Puede haber sido eliminada o nunca existió.',
    'common.loadingImages': 'Cargando imágenes...',
    
    // Theme/Language
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'lang.en': 'English',
    'lang.es': 'Español',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.profile': 'Perfil',
    'settings.profileDesc': 'Gestionar tu información de perfil',
    'settings.notifications': 'Notificaciones',
    'settings.notificationsDesc': 'Controlar tus preferencias de notificación',
    'settings.privacy': 'Privacidad',
    'settings.privacyDesc': 'Gestionar tu configuración de privacidad',
    'settings.appearance': 'Apariencia',
    'settings.appearanceDesc': 'Personalizar la apariencia de la aplicación',
    'settings.language': 'Idioma',
    'settings.languageDesc': 'Elegir tu idioma preferido',
    'settings.logout': 'Cerrar Sesión',
    'settings.displayName': 'Nombre para Mostrar',
    'settings.displayNamePlaceholder': 'Ingresa tu nombre para mostrar',
    'settings.bio': 'Biografía',
    'settings.bioPlaceholder': 'Cuéntanos sobre ti',
    'settings.emailNotifications': 'Notificaciones por Email',
    'settings.emailNotificationsDesc': 'Recibir notificaciones por email',
    'settings.pushNotifications': 'Notificaciones Push',
    'settings.pushNotificationsDesc': 'Recibir notificaciones push en tu dispositivo',
    'settings.pollReminders': 'Recordatorios de Encuestas',
    'settings.pollRemindersDesc': 'Recibir recordatorios sobre encuestas en las que participaste',
    'settings.privateProfile': 'Perfil Privado',
    'settings.privateProfileDesc': 'Solo seguidores pueden ver tu actividad',
    'settings.showActivity': 'Mostrar Estado de Actividad',
    'settings.showActivityDesc': 'Permitir que otros vean cuándo estás activo',
    'settings.theme': 'Tema',
    'settings.displayLanguage': 'Idioma de Visualización',
    'settings.saveChanges': 'Guardar Cambios',
    
    // Spin Wheel
    'spin.title': 'Gira la',
    'spin.titleHighlight': 'Ruleta',
    'spin.subtitle': '¿No puedes decidir? ¡Deja que el destino elija! Agrega tus opciones y dale a la ruleta un giro.',
    'spin.spin': 'GIRAR',
    'spin.spinning': '...',
    'spin.currentOptions': 'Opciones Actuales',
    'spin.quickTemplates': 'Plantillas Rápidas',
    'spin.optionPlaceholder': 'Opción',
    'spin.addOption': 'Agregar',
    'spin.add': 'Agregar',
    'spin.addToWheel': 'Agregar a la Ruleta',
    'spin.yesOrNo': 'Sí o No',
    'spin.foodChoice': 'Comida',
    'spin.activities': 'Actividades',
    'spin.numbers': 'Números 1-6',
    'spin.theWheelHasSpoken': '¡La ruleta ha hablado!',
    'spin.spinAgain': 'Girar de Nuevo',
    'spin.enterAtLeastTwoOptions': '¡Ingresa al menos 2 opciones para comenzar a girar!',
    'spin.minimumTwoOptions': 'Mínimo 2 opciones requeridas',
    'spin.maximumTwelveOptions': 'Máximo 12 opciones permitidas',
    'spin.pleaseEnterAnOption': 'Por favor ingresa una opción',
    'spin.optionTextCannotBeEmpty': 'El texto de la opción no puede estar vacío',
    'spin.addAtLeastTwoOptionsToSpin': 'Agrega al menos 2 opciones para girar',
    'spin.optionsCount': 'opciones (mínimo 2 requeridas para girar)',
    'spin.enterAnOption': 'Ingresa una opción...',
    'spin.addOptionAfterThis': 'Agregar opción después de esta',
    'spin.removeOption': 'Eliminar opción',
    'spin.configureOptions': 'Configurar Opciones',
    'spin.spinWheel': 'Girar Ruleta',
    'spin.continueToWheel': 'Continuar a la Ruleta',
    'spin.editOptions': 'Editar Opciones',

    // Polls & Rankings
    'poll.yourRankingSubmitted': 'Tu ranking ha sido enviado y no puede ser cambiado',
    'poll.pollsInvitedTo': 'Encuestas a las que estoy invitado',
    'poll.myPrivatePolls': 'Mis Encuestas Privadas',
    'poll.myPublicPolls': 'Mis Encuestas Públicas',
    'poll.onlyLinkAccess': 'Solo las personas con este enlace pueden ver esta encuesta',
    'poll.copyInviteLink': 'Copiar enlace de invitación',
    'poll.acceptInvite': 'Aceptar invitación y ver encuesta',
    'poll.invalidInvite': 'Enlace de invitación inválido o expirado',
    'poll.noAccess': 'No tienes acceso a esta encuesta',
    'poll.noRankings': 'No hay rankings enviados aún',
    'poll.submitRanking': 'Enviar Ranking',
    'poll.rankPoll': 'Encuesta de Ranking',
    'poll.votePoll': 'Votar Encuesta',
    'poll.private': 'Privada',
    'poll.public': 'Pública',
    'poll.emojiOptional': 'Emoji (opcional)',
    'poll.share': 'Compartir',
    'poll.copied': '¡✓ Copiado!',
    'poll.delete': 'Eliminar',
    'poll.deleteConfirm': '¿Estás seguro de que quieres eliminar esta encuesta? Esto no se puede deshacer.',
    'poll.cancel': 'Cancelar',
    'poll.viewPoll': 'Ver encuesta',
    'poll.noVotesYet': 'Sin votos aún. ¡Sé el primero!',
    'poll.active': 'Activa',
    'poll.ended': 'Finalizada',
    'poll.myPolls': 'Mis Encuestas',
    'poll.deletePoll': 'Eliminar encuesta',
    'poll.voteOnPoll': 'Votar',
    'poll.results': 'Resultados',
    'poll.dangerZone': 'Zona de peligro',
    
    // Create Poll Form
    'create.titleRequired': 'El título del ranking es requerido',
    'create.pollTitleRequired': 'El título de la encuesta es requerido',
    'create.titleMinLength': 'El título debe tener al menos 3 caracteres',
    'create.titleMaxLength': 'El título debe tener menos de 100 caracteres',
    'create.minOptions': 'Se requieren al menos 2 opciones',
    'create.maxOptions': 'Máximo 10 opciones permitidas',
    'create.duplicateOptions': 'No se permiten opciones duplicadas',
    'create.minParticipants': 'Las encuestas privadas requieren al menos un participante',
    'create.failed': 'Falló al crear la encuesta. Por favor intenta de nuevo.',
    'create.failedRanking': 'Falló al crear el ranking. Por favor intenta de nuevo.',
    'create.creating': 'Creando...',
    'create.optionRequired': 'La opción es requerida',
    'create.optionMinLength': 'La opción debe tener al menos 1 caracter',
    'create.newVote': 'Crear una Nueva Votación',
    'create.newRanking': 'Crear un Nuevo Ranking',
    'create.newPoll': 'Crear una Nueva Encuesta',
    'create.description': 'Comparte tus pensamientos y reúne opiniones de tu comunidad',
    'create.back': 'Volver',
    
    // My Polls
    'myPolls.createdBy': 'Creado por',
    'myPolls.noPolls': 'No has creado ninguna encuesta aún',
    'myPolls.startCreating': '¡Comienza creando tu primera encuesta!',
    'myPolls.createFirst': 'Crea tu Primera Encuesta',

    // Navbar specific
    'nav.hello': 'Hola',
    'nav.changeName': 'Cambiar nombre',
    'nav.createVote': 'Crear Votación',
    'nav.createRanking': 'Crear Ranking',
    'nav.createRating': 'Crear Rating',
    'nav.spinWheel': 'Girar Ruleta',
    'nav.createVersus': 'Crear Versus',
    'nav.votes': 'Votaciones',
    'nav.ranking': 'Ranking',
    'nav.ratings': 'Ratings',
    'nav.versus': 'Versus',
    'nav.vote': 'Votar',
    'nav.changeYourName': 'Cambiar tu nombre',
    'nav.yourNewName': 'Tu nuevo nombre...',
    'nav.save': 'Guardar',
    'nav.yourName': 'Tu nombre',
    'nav.placeholder': 'Ingresa tu nombre',

    // Home page specific
    'home.subtitle': 'Crea encuestas, rankings, ratings y ruletas — compártelas con cualquiera.',
    'home.recentActivity': 'Actividad reciente',
    'home.noActivityYet': 'Sin actividad aún — ¡sé el primero en crear algo!',
    'home.votesDesc': 'Haz una pregunta, deja que la gente elija una respuesta',
    'home.rankingDesc': 'Deja que la gente clasifique las opciones por preferencia',
    'home.ratingsDesc': 'Califica y compara elementos con estrellas',
    'home.spinDesc': 'Gira para decidir al azar',
    'home.rankingBadge': 'Ranking',
    'home.voteBadge': 'Voto',

    // PollCard specific
    'poll.closingIn': 'Cierra en',
    'poll.votes': 'votos',

    // Versus specific
    'versus.tournamentCreated': 'Torneo creado',
    'versus.completePreviousRound': 'Completa la ronda anterior primero',
    'versus.completeAllDuels': 'Completa todos los duelos antes de enviar',
    'versus.shareResult': 'Compartir Resultado',
    'versus.generating': 'Generando...',
    'versus.copied': '¡Copiado!',
    'versus.downloaded': '¡Descargado!',
    'versus.error': 'Error',
    'versus.expired': 'Expirado',
    'versus.completed': 'Completado',
    'versus.loadingTournament': 'Cargando torneo...',
    'versus.by': 'por',
    'versus.options': 'opciones',
    'versus.share': 'Compartir',
    'versus.comp': 'Comp',
    'versus.submitBracket': 'Enviar Bracket',
    'versus.submit': 'Enviar',
    'versus.result': 'Resultado',
    'versus.bracketOf': 'Bracket de',
    'versus.anonymous': 'Anónimo',
    'versus.days': 'd',
    'versus.hours': 'h',
    'versus.minutes': 'm',
    'versus.seconds': 's',

    // Explore page
    'explore.title': 'Explorar Encuestas',
    'explore.subtitle': 'Descubre y participa en encuestas de la comunidad',
    'explore.searchPlaceholder': 'Buscar encuestas por título u opciones...',
    'explore.sortBy': 'Ordenar por:',
    'explore.mostRecent': 'Más Recientes',
    'explore.newlyCreated': 'Encuestas recién creadas',
    'explore.mostPopular': 'Más Populares',
    'explore.highestVoteCount': 'Mayor cantidad de votos',
    'explore.trending': 'Tendencias',
    'explore.popularRecent': 'Encuestas populares recientes',
    'explore.endingSoon': 'Terminan Pronto',
    'explore.pollsClosingSoon': 'Encuestas que cierran pronto',
    'explore.found': 'Encontradas',
    'explore.pollsMatching': 'encuestas que coinciden con',
    'explore.showing': 'Mostrando',
    'explore.polls': 'encuestas',
    'explore.noPollsFound': 'No se encontraron encuestas',
    'explore.noPollsAvailable': 'No hay encuestas disponibles',
    'explore.tryAdjusting': 'Intenta ajustar tus términos de búsqueda o explora todas las encuestas',
    'explore.beFirst': '¡Sé el primero en crear una encuesta y comenzar!',
    'explore.clearSearch': 'Limpiar Búsqueda',
    'explore.createPoll': 'Crear una Encuesta',

    // My Polls page
    'myPolls.noPublicPolls': 'Sin encuestas públicas aún',
    'myPolls.createFirstPublic': '¡Crea tu primera encuesta pública para compartirla con todos!',
    'myPolls.createPoll': 'Crear Encuesta',
    'myPolls.noPrivatePolls': 'Sin encuestas privadas aún',
    'myPolls.createPrivateDesc': 'Crea una encuesta privada para compartirla solo con participantes específicos.',
    'myPolls.createPrivatePoll': 'Crear Encuesta Privada',
    'myPolls.invitedTo': 'Encuestas a las que estoy invitado',
    'myPolls.noPendingInvites': 'Sin invitaciones pendientes',
    'myPolls.invitesDesc': 'Cuando alguien te invite a una encuesta privada, aparecerá aquí.',

    // EmptyPollsState
    'empty.createFirstPoll': '¡Crea tu Primera Encuesta!',
    'empty.description': 'Comparte tu opinión y descubre qué piensa tu comunidad. Es fácil, rápido y divertido.',
    'empty.createPollNow': 'Crear Encuesta Ahora',
    'empty.tryWheel': 'Probar la Ruleta',
    'empty.easyVoting': 'Votación Fácil',
    'empty.easyVotingDesc': 'Crea encuestas en segundos con múltiples opciones',
    'empty.decisionWheel': 'Ruleta de Decisiones',
    'empty.decisionWheelDesc': 'Deja que el destino decida por ti',
    'empty.trending': 'Tendencias',
    'empty.trendingDesc': 'Descubre las encuestas más populares',
    'empty.bestDecisions': 'Las mejores decisiones se toman juntos',

    // Votes page
    'votes.title': 'Votaciones',
    'votes.subtitle': 'Vota por tus opciones favoritas',
    'votes.createVote': 'Crear Votación',
    'votes.recent': 'Recientes',
    'votes.loadingVotes': 'Cargando votaciones...',
    'votes.noVotesYet': 'Sin votaciones aún',
    'votes.beFirst': '¡Sé el primero en crear una votación!',

    // Create Poll Form
    'form.pollBasics': 'Datos de la Encuesta',
    'form.pollType': 'Tipo de Encuesta',
    'form.votePoll': 'Encuesta de Votación',
    'form.votePollDesc': 'Cada persona elige una opción',
    'form.rankPoll': 'Encuesta de Ranking',
    'form.rankPollDesc': 'Ordena todas las opciones por preferencia',
    'form.pollTitle': 'Título de la Encuesta',
    'form.whatsPollAbout': '¿De qué trata tu encuesta?',
    'form.whatsRankingAbout': '¿De qué trata tu ranking?',
    'form.searchStockImages': '📷 Buscar Imágenes de Stock',
    'form.removeTitleImage': 'Eliminar imagen de título',
    'form.titleImagePreview': 'Vista previa de imagen de título',
    'form.characters': 'caracteres',
    'form.description': 'Descripción (Opcional)',
    'form.addDetailsPoll': 'Agrega más detalles sobre tu encuesta...',
    'form.addDetailsRanking': 'Agrega más detalles sobre tu ranking...',
    'form.expiration': 'Expiración',
    'form.willClose': 'La encuesta se cerrará automáticamente después de la duración seleccionada',
    'form.pollOptions': 'Opciones de la Encuesta',
    'form.addOptionsRank': 'Agrega al menos 2 opciones para clasificar. Puedes incluir texto, emoji o subir una imagen para cada opción.',
    'form.addOptions': 'Agrega al menos 2 opciones. Puedes incluir texto, emoji o subir una imagen para cada opción.',
    'form.option': 'Opción',
    'form.stockImages': '📷 Imágenes de Stock',
    'form.optionPreview': 'Vista previa de opción',
    'form.removeImage': 'Eliminar imagen',
    'form.youNeedAtLeast': 'Necesitas al menos 2 opciones',
    'form.removeOption': 'Eliminar opción',
    'form.addOption': '+ Agregar Opción',
    'form.visibilityPrivacy': 'Visibilidad y Privacidad',
    'form.public': 'Pública - Cualquiera con el enlace puede ver y votar',
    'form.publicRank': 'Pública - Cualquiera con el enlace puede ver y clasificar',
    'form.private': 'Privada - Solo los participantes invitados pueden ver y votar',
    'form.privateRank': 'Privada - Solo los participantes invitados pueden ver y clasificar',
    'form.privateLock': '🔒 Solo las personas con las que compartas el enlace pueden ver esta encuesta',
    'form.privateLockRank': '🔒 Solo las personas con las que compartas el enlace pueden ver este ranking',
    'form.privateWarning': '⚠️ Las encuestas privadas requieren al menos un participante',
    'form.privateWarningRank': '⚠️ Los rankings privados requieren al menos un participante',
    'form.anonymousVoting': 'Votación anónima (los votos de los participantes están ocultos)',
    'form.inviteParticipants': 'Invitar Participantes',
    'form.enterEmail': 'Ingresa email o nombre de usuario',
    'form.invitedParticipants': 'Participantes Invitados:',
    'form.removeParticipant': 'Eliminar participante',
    'form.duration.15min': '15 minutos',
    'form.duration.30min': '30 minutos',
    'form.duration.1h': '1 hora',
    'form.duration.3h': '3 horas',
    'form.duration.6h': '6 horas',
    'form.duration.12h': '12 horas',
    'form.duration.24h': '24 horas',
    'form.duration.48h': '48 horas',
    'form.duration.7d': '7 días',
    'form.onlyJpgPng': 'Solo se permiten imágenes JPG y PNG',
    'form.imageSize': 'El tamaño de la imagen debe ser menor a 5MB',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Check for saved language preference or default to English
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
      setLanguageState(savedLanguage);
    } else {
      // Check browser language
      const browserLang = navigator.language.toLowerCase();
      if (browserLang.startsWith('es')) {
        setLanguageState('es');
      } else {
        setLanguageState('en');
      }
    }
  }, []);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
    document.documentElement.setAttribute('lang', newLanguage);
  };

  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'es' : 'en';
    setLanguage(newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
